[package]
name = "rover_server"
version = "0.1.0"
authors = ["Leonti Bielski"]

[dependencies]
crossbeam-channel = "0.2"
bufstream = "0.1"
tokio = "0.1.11"
futures = "0.1.25"
bytes = "0.4.10"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
